default_stages: [commit, push]
exclude: |
  (?x)(
    ^static/ |
    /static/ |
    /migrations/
  ) |
  pdfsizeopt
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        additional_dependencies:
        - prettier@2.6.2
        - '@trivago/prettier-plugin-sort-imports@3.2.0'
        exclude: node_modules
        types_or: [javascript, ts]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports # TODO: remove this
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
