default_stages: [commit, push]
exclude: |
  (?x)(
    ^static/ |
    /static/ |
    /migrations/
  ) |
  pdfsizeopt
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        additional_dependencies:
        - prettier@2.6.2
        - '@trivago/prettier-plugin-sort-imports@3.2.0'
        exclude: node_modules
        types_or: [javascript, ts]
